# -*- coding: utf-8 -*-
"""ML_Task_Level_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZP9yO-AYYKtk5z5GptPlKisCh-rfPKOr

**FINE TUNING WITH LoRA**
"""

!pip install transformers datasets peft accelerate

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %run "/content/drive/MyDrive/Colab_Notebooks/ML_Task_Level_1.ipynb"
# %run "/content/drive/MyDrive/Colab_Notebooks/ML_Task_Level_2.ipynb"

from datasets import load_dataset

ds = load_dataset("takala/financial_phrasebank","sentences_allagree",revision="refs/pr/10")

print(ds)

"""**Create Train-test-split**"""

ds = ds['train'].train_test_split(test_size=0.2)
print(ds)

"""**Tokenize with the distilbert-base-uncased tokenizer**"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(tokens):
  return tokenizer(tokens['sentence'],truncation=True,padding="max_length")
token_ids = ds.map(tokenize,batched=True,load_from_cache_file=False)

"""**Load model**"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased",num_labels=3)

print(set(token_ids["train"]["label"]))

"""**Apply LoRA**"""

from peft import LoraConfig,get_peft_model

config = LoraConfig(r=8,lora_alpha=16,target_modules=["q_lin","v_lin"],lora_dropout=0.1,bias="none",task_type="SEQ_CLS")

model = get_peft_model(model,config)

"""**Print how many parameters are trainable**"""

model.print_trainable_parameters()

"""**Training**"""

from transformers import TrainingArguments

training = TrainingArguments(
    output_dir = "./output",
    learning_rate = 2e-5,
    per_device_train_batch_size = 20,
    per_device_eval_batch_size = 20,
    num_train_epochs = 10,
    save_strategy = "epoch",
    logging_dir = "./log"
)

from transformers import Trainer

trainer = Trainer(
    model = model,
    args = training,
    train_dataset = token_ids['train'],
    eval_dataset = token_ids['test']
)

trainer.train()

"""**Model evaluation**"""

Evaluation = trainer.predict(token_ids['test'])

print(Evaluation)

"""**Comparision between Level-1 level-2 and Level-3**"""

from sklearn.metrics import classification_report
import pandas as pd

report1 = classification_report(y_test,y_pred,output_dict=True)
level1 = report1["macro avg"]["f1-score"]
level1_acc = report1["accuracy"]


labels = {
    "negative" : 0,
    "neutral" : 1,
    "positive" : 2
}

predictions = [labels[p] for p in predictions]
report2 = classification_report(y_test,predictions,output_dict=True)
level2 = report2["macro avg"]["f1-score"]
level2_acc = report2["accuracy"]

report3 = classification_report(y_test,y_pred,output_dict=True)
level3 = report3["macro avg"]["f1-score"]
level3_acc = report3["accuracy"]

comparision = pd.DataFrame({
    "Model": ["Level-1","Level-2","Level-3"],
    "F1-Score": [level1,level2,level3],
    "Accuracy": [level1_acc,level2_acc,level3_acc]
})

print(comparision)

"""**Reason of using LoRA(Low Rank Adaption) instead of full fine-tuning**

---
LoRA is used instead of full-tuning because it is faster and uses less memory.In full fine-tuning,all the parameters of the model are trained,which takes a lot of time and also it requires a powerfull GPU.

LoRA solves the problem by freezing the entire original model weights and introduces small trainable metrices into specific layers like attention layers.This allows the model to adapt new task without modifying the entire netword.LoRA enable faster training,lower memory usage and it makes feasible to fine-tune large models.

So LoRA is efficient and smart way to fine-tune large models with less computation and good performance.




**Changes**

---



The main changes LoRA makes that it does not moify the original weights. It only adds small updates that help the model learn the new task.This way the model keeps the previous knowledge and improves on the new dataset.
"""